## Schedule overview

| Week       | Topic                                |                       |                                        |                                        |     |
|------------|------------|------------|------------|------------|------------|
| 1          | Quantitative methods and uncertainty | [Slides](slides/w01/) | [Tutorial](tutorials/tutorial-w01.qmd) |                                        |     |
| 2          | Data wrangling                       | [Slides](slides/w02/) | [Tutorial](tutorials/tutorial-w02.qmd) |                                        |     |
| 3          | Data visualisation                   | [Slides](slides/w03/) | [Tutorial](tutorials/tutorial-w03.qmd) |                                        |     |
| 4          | Statistical modeling basics          | [Slides](slides/w04/) | [Tutorial](tutorials/tutorial-w04.qmd) |                                        |     |
| 5          | Categorical predictors               | [Slides](slides/w05/) | [Tutorial](tutorials/tutorial-w05.qmd) | [F1](https://github.com/uoelel/qml-f1) |     |
| 6 Catch up | *No classes*                         |                       |                                        |                                        |     |
| 7          | Binary outcomes                      | [Slides](slides/w07/) | [Tutorial](tutorials/tutorial-w07.qmd) |                                        |     |
| 8          | Multiple predictors and interactions | [Slides](slides/w08/) | [Tutorial](tutorials/tutorial-w08.qmd) |                                        | [S1](https://github.com/uoelel/qml-s1/)  |
| 9          | Continuous predictors                | [Slides](slides/w09/) | [Tutorial](tutorials/tutorial-w09.qmd) |                                        |     |
| 10         | Research process: an overview                   | [Slides](slides/w10/) | [Tutorial](tutorials/tutorial-w10.qmd) | [F2](https://github.com/uoelel/qml-f2/)                                     |     |
| 11         | Obtaining p-values (optional)        | [Slides](slides/w11/) | [Tutorial](tutorials/tutorial-w11.qmd) |                                        |     |
| 12         |                                      |                       |                                        |                                        | S2  |

## Weekly schedule

### Week 1: Quantitative methods and uncertainty

::: {.callout-important collapse="false"}
#### Learning Objectives

**Questions**

-   What is quantitative data analysis?
-   What is the inference process?
-   How can we talk about uncertainty and variability?
-   Which are the limits of quantitative methods?

**Skills**

-   Think critically about statistics, uncertainty and variability.
-   Use R to perform simple calculations.
-   Master the basics of the programming language R.
-   Use RStudio.
:::

::: {.callout-note collapse="false"}
#### Homework

**Course website**

-   Carefully read the [homepage](https://uoelel.github.io/qml/).

-   Familiarise yourself with this *Course content* page (note that the materials will be updated throughout the course).

**Intake form**

-   **You must complete the intake form before coming to the Tuesday lecture.**
-   The link to the form can be found on the Learn website.

**Install R and RStudio**

-   For this course, you need to install both R and RStudio.
-   **NOTE**: If you have installed either R or RStudio prior to January 2023, please make sure you delete both R and RStudio from your laptop.
-   Please, follow the instructions in the [Setup](setup.qmd) page.
:::

::: {.callout-tip collapse="false"}
#### Materials

-   [Lecture slides](slides/w01/).
-   [Workshop tutorial](tutorials/tutorial-w01.qmd).
:::

::: {.callout-tip collapse="false"}
#### Suggested readings

**Main textbooks**

-   Statistics for Linguists with R, by Bodo Winter (**S4LR**) Ch. 1. \[via library\]
-   R for Data Science (**R4DS**) [Ch. 1](https://r4ds.hadley.nz/intro.html), [Ch. 2](https://r4ds.hadley.nz/data-visualize). \[online book\]
-   Statistical (Re)thinking, by Richard McElreath (**SReT**), Ch. 1. \[via library\]

**From the lecture**

-   [Ellis and Levy 2008](https://www.informingscience.org/Publications/438?Source=%2FJournals%2FInformingSciJ%2FArticles%3FVolume%3D11-2008). Framework of Problem-Based Research: A Guide for Novice Researchers on the Development of a Research-Worthy Problem
-   [Silberzahn et al. 2018](https://doi.org/10.1177/2515245917747646). Many Analysts, One Data Set: Making Transparent How Variations in Analytic Choices Affect Results
-   [Coretta et al. 2023](https://doi.org/10.31234/osf.io/q8t2k). Multidimensional signals and analytic flexibility: Estimating degrees of freedom in human speech analyses
-   [Cumming 2014](https://doi.org/10.1177%2F0956797613504966). The New Statistics: Why and How
-   [Kurschke and Liddell 2018](https://doi.org/10.3758/s13423-016-1221-4). The Bayesian New Statistics: Hypothesis testing, estimation, meta-analysis, and power analysis from a Bayesian perspective

**Replication**

- 👉 [Assessing the replication landscape in experimental linguistics](https://doi.org/10.31234/osf.io/fzngs).
- [The Stark realities of reproducible statistically orientated sociological research: Some newer rules of the sociological method](
https://doi.org/10.1177/20597991221111681).

**Other**

- [Methods as theory](https://stefanocoretta.github.io/post/methods-as-theory/).
- Molnar 2022. Modeling Mindsets: The many cultures of learning from data.
-   [Darwin Holmes 2020](https://doi.org/10.34293/education.v8i4.3232). Researcher Positionality - A Consideration of Its Influence and Place in Qualitative Research - A New Researcher Guide
-   [Jafar 2018](https://doi.org/10.1136/emermed-2017-207158). What is positionality and should it be expressed in quantitative studies?
:::

### Week 2: Data wrangling

::: {.callout-important collapse="false"}
#### Learning Objectives

**Questions**

-   What are the types of statistical variables?
-   Which summary measures are appropriate for which types of variables?
-   What are common measures central tendency?
-   What are common measures of dispersion?

**Skills**

-   Organise files efficiently.
-   Import tabular data in R.
-   Obtain mean, median, mode, range and standard deviation.
-   Use R scripts to save and reuse code.
:::

::: {.callout-tip collapse="false"}
#### Materials

-   [Lecture slides](slides/w02/).
-   [Workshop tutorial](tutorials/tutorial-w02.qmd).
-   Workshop files (right-click and download):
    -   [shallow.csv](data/shallow.csv)
:::

::: {.callout-tip collapse="false"}
#### Suggested readings

**Main textbooks**

-   **S4LR** Ch. 3. \[via library\]
-   **R4DS** [Ch. 3](https://r4ds.hadley.nz/workflow-basics) and [Ch. 4](https://r4ds.hadley.nz/data-transform.html). \[online book\]
:::

### Week 3: Data visualisation

::: {.callout-important collapse="false"}
#### Learning Objectives

**Questions**

-   What are the principles of good data visualisation?
-   Which are the main components of a plot?
-   Which are the appropriate plots for different types of data?
-   How can we visualise uncertainty?

**Skills**

-   Create common types of plots with ggplot2.
-   Use colour and shape to effectively convey meaning.
-   Describe a plot in writing and comment on observable patterns.
-   Create styled HTML reports.
:::

::: {.callout-tip collapse="false"}
#### Materials

-   [Lecture slides](slides/w03/).
-   [Workshop tutorial](tutorials/tutorial-w03.qmd).
-   Workshop files (right-click and download):
    -   [polite.csv](data/polite.csv)
    -   [glot_status.rds](data/glot_status.rds)
:::

::: {.callout-tip collapse="false"}
#### Suggested readings

**Main textbooks**

-   **R4DS** [Ch. 2](https://r4ds.hadley.nz/data-visualize.html). \[online book\]
-   [ggplot2](https://ggplot2.tidyverse.org) documentation.

**From the lecture**

-   [Spiegelhalter 2020](https://www.penguin.co.uk/books/294857/the-art-of-statistics-by-spiegelhalter-david/9780241258767). *The Art of Statistics: Learning from Data.*

**Other**

- [Gabry et al 2019](https://doi.org/10.1111/rssa.12378). Visualization in Bayesian workflow.
- [Politzer-Ahles and Piccini](https://doi.org/10.1016/j.wocn.2018.05.002). On visualizing phonetic data from repeated measures experiments with multiple random effects.
-   [Fundamentals of Data Visualisation](https://clauswilke.com/dataviz/).
-   **Data viz catalogues**
    -   [Directory of visualisations](https://clauswilke.com/dataviz/directory-of-visualizations.html)
    -   [Data viz catalogue](https://datavizcatalogue.com/index.html)
    -   [Data Viz project](https://datavizproject.com)
    -   [Top 50](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html)
    -   [Data Viz](https://datavizm20.classes.andrewheiss.com/)
-   **Tutorials**
    -   [Raincloud plots](https://wellcomeopenresearch.org/articles/4-63)
    -   [Labels](https://www.cararthompson.com/talks/user2022/)
    -   [Graphic design](https://rstudio-conf-2022.github.io/ggplot2-graphic-design/)
-   **Colour**
    -   [ColorBrewer2](https://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3).
    -   [MetBrewer](https://github.com/BlakeRMills/MetBrewer)
    -   [Use colour wisely](https://albert-rapp.de/post/2022-02-19-ggplot2-color-tips-from-datawrapper/).
-   **Caveats**
    -   [Same stats different data](https://www.autodesk.com/research/publications/same-stats-different-graphs).
    -   [Behind bars](https://stats.stackexchange.com/questions/349422/does-it-make-sense-to-add-error-bars-in-a-bar-chart-of-frequencies/367889#367889).
    -   [Issues with error bars](https://www.data-to-viz.com/caveat/error_bar.html).
    -   [I've stopped using boxplots](https://nightingaledvs.com/ive-stopped-using-box-plots-should-you/).
:::

### Week 4: Statistical modeling basics

::: {.callout-important collapse="false"}
#### Learning Objectives

**Questions**

-   What are probability distributions?
-   How can we describe probability distributions with statistical parameters?
-   What are the frequentist and Bayesian view of statistical parameters?
-   How can we estimate parameters using statistical models?

**Skills**

-   Transform data by creating new columns (mutate) and filtering based on specific values (filter).
-   Use logical operators to transform data.
-   Fit a statistical model to estimate the mean and standard deviation of a Gaussian variable with `brm()`.
-   Interpret the summary of the model and understand the meaning of the reported estimates.
:::

::: {.callout-tip collapse="false"}
#### Materials

-   [optional] [The Golem of Prague](https://youtu.be/FdnMWdICdRs?si=qprHmzSkHSln0_-z) (video lecture of SreT Ch 1).
-   [Lecture slides](slides/w04/).
-   [Workshop tutorial](tutorials/tutorial-w04.qmd).
-   Workshop files (right-click and download):
    -   [alb_vot.csv](data/alb_vot.csv)
:::

::: {.callout-tip collapse="false"}
#### Suggested readings

**Main textbooks**

-   **R4DS** [Ch. 2](https://r4ds.hadley.nz/data-visualize.html). \[online book\]
-   [ggplot2](https://ggplot2.tidyverse.org) documentation.
-   **S4LR** Ch 3. \[via library\]
-   **SReT** Ch 2, sparingly (we have not covered everything in the chapter yet). \[via library\]

**Other**

The following resources will be helpful throughout the course. Note they cover aspects that we have not yet discussed (some will be in the following weeks, others won't be due to time), but **do bookmark these** because they will be valuable when you will be working on your dissertation.

- [Linear Models and Mixed Models with R](https://www.bodo-winter.net/tutorials.html) tutorials (1 and 2) by Bodo Winter (author of S4LR) for a general overview of the type of models we focus on in this course.
- [One Thousand and One names](https://stefanocoretta.github.io/post/2022-07-22-one-thousand-and-one-names/): table with naming conventions for different types of linear models.
- [Linear Models: A cheat-sheet](https://stefanocoretta.github.io/post/2021-08-21-regression-models-a-cheat-sheet/): use this to find out which building blocks you need for your linear model.
:::

### Week 5: Categorical predictors

::: {.callout-warning}
#### Formative assessment 1

-   **DUE on Thu 19 October at noon**.

-   Formative assessment 1 requires you to complete a few guided exercises of the type that will be included in Summative 1.

-   Find instructions and data here: <https://github.com/uoelel/qml-f1>
:::

::: {.callout-important collapse="false"}
#### Learning Objectives

**Questions**

-   How do we model variables using categorical predictors?
-   Which are the most common coding systems for categorical predictors?
-   How do we interpret the model output when there are categorical predictors?
-   How can we quickly check model goodness?

**Skills**

-   Master contrast coding in R for categorical predictors.
-   Understand treatment coding.
-   Fit, interpret and plot models with a categorical predictor.
-   Reporting of model specification and results.
:::

::: {.callout-tip collapse="false"}
#### Materials

-   [Lecture slides](slides/w05/).
-   [Workshop tutorial](tutorials/tutorial-w05.qmd).
-   Workshop files (right-click and download):
    -   [senses_valence.csv](data/senses_valence.csv)
:::

::: {.callout-tip collapse="false"}
#### Suggested readings

**Main textbooks**

-   **R4DS** [Ch. 17](https://r4ds.hadley.nz/factors.html). \[online book\]
-   **S4LR** Ch 7. \[via library\]
-   **SReT** Sec 5.3. \[via library\]

**Other**

- [Factors, coding and contrasts](https://stefanocoretta.github.io/post/contrasts/): blog post on factors in linear models. It also discusses interactions, which we will cover in Weeks 8-9.
:::

### Week 6: Catch-up Week

::: {.callout-note collapse="false"}
#### Homework

There is no homework as such, so take the time to revise the materials and/or catch up with the previous weeks' materials.

There will be no classes.
:::

### Week 7: Binary outcomes



::: {.callout-important collapse="false"}
#### Learning Objectives

**Questions**

-   How can we visualise proportions of binary outcomes (yes/no, correct/incorrect, ...)?
-   Which distribution do binary outcomes follow?
-   What is the relationship between probabilities and log-odds?
-   How do we interpret log-odds and odds?

**Skills**

-   Plot binary data as proportions in ggplot2.
-   Pivot data from wide to long with tidyr.
-   Fit, interpret and plot linear models with binary outcome variables, using the Bernoulli distribution family.
-   Convert between log-odds, odds and probabilities.
:::

::: {.callout-tip collapse="false"}
#### Materials

-   [Lecture slides](slides/w07/).
-   [Workshop tutorial](tutorials/tutorial-w07.qmd).
-   Workshop files (right-click and download):
    -   [takete_maluma.txt](data/takete_maluma.txt).
:::

::: {.callout-tip collapse="false"}
#### Suggested readings

**Main textbooks**

-   **R4DS** [Ch. 6](https://r4ds.hadley.nz/data-tidy). \[online book\]
-   **S4LR** Ch 12. \[via library\]
-   **SReT** Ch 11. \[via library\]
:::

### Week 8: Multiple predictors and interactions

::: {.callout-warning}
#### Summative 1: Week 8 (Thu 9 November at noon)

**Due on Thursday 9 November at noon**

The first summative contains a series of guided exercises that cover things done in Weeks 1 to 7.

You can find the instructions and data for the first summative here: <https://github.com/uoelel/qml-s1/>.

:::

::: {.callout-important collapse="false"}
#### Learning Objectives

**Questions**

-   What is a factorial design?
-   How do we estimate and interpret the effects of multiple predictors?
-   How do we deal with situations when one predictor's effect is different, depending on the value of the other predictor?
-   How can such interactions between predictors be built into our models?
-   How do we interpret model estimates of interactions?

**Skills**

-   Run and interpret models with multiple predictors.
-   Interpret interactions between two predictors.
-   Plot posterior and conditional probabilities from models with interactions.
-   Practice transforming and back-transforming variables.
:::

::: {.callout-tip collapse="false"}
#### Materials

-   [Lecture slides](slides/w08/).
-   [Workshop tutorial](tutorials/tutorial-w08.qmd).
-   Workshop files (right-click and download):
    -   [shallow.csv](data/shallow.csv).
    -   [dur-ita-pol.csv](data/dur-ita-pol.csv).
:::

### Week 9: Continuous predictors and interactions

::: {.callout-important collapse="false"}
#### Learning Objectives

**Questions**

-   How do we model predictors that aren't categorical, but continuous?
-   How do we interpret model estimates for continuous predictors?
-   How do we fit and interpret interactions involving continuous predictors?

**Skills**

-   Centre continuous predictors.
-   Run and interpret models with continuous predictors.
-   Interpret interactions that are categorical \* continuous (in the lecture) and continuous \* continuous (in the tutorial).
:::

::: {.callout-tip collapse="false"}
#### Materials

-   [Lecture slides](slides/w09/).
-   [Workshop tutorial](tutorials/tutorial-w09.qmd).
-   Workshop files (right-click and download):
    -   [si.csv](data/si.csv).
:::

### Week 10: Research process - An overview

::: {.callout-warning collapse="false"}
#### Formative assessment 2

-   **DUE on Thursday 23 November at noon**.

-   F2 requires you to read, plot and model data. Summative 2 will have the same format.
:::

::: {.callout-note collapse="false"}
#### Homework

Please, read the following before coming to class on Wednesday (there will be no lecture on Tuesday).

- [Stroop Effect in Language](https://doi.org/10.1016/B0-08-044854-2/00871-3)
- [Half a Century of Research on the Stroop Effect: An Integrative Review](http://www.ezproxy.is.ed.ac.uk/login?url=http://ovidsp.ovid.com.ezproxy.is.ed.ac.uk/ovidweb.cgi?T=JS&CSC=Y&NEWS=N&PAGE=fulltext&AN=00006823-199103000-00001&D=ovft), pp 163--165 plus one extra section of your choice.
:::

::: {.callout-tip collapse="false"}
#### Materials

-   [Lecture slides](slides/w10/).
-   [Workshop tutorial](tutorials/tutorial-w10.qmd).
-   Workshop files: <https://github.com/uoelel/qml-stroop>.
:::

::: {.callout-tip collapse="false"}
#### Useful resources

The following resources are a useful summaries of conceptual, practical and terminological aspects of linear models in general.

- [Linear Models Illustrated](https://stefanocoretta.shinyapps.io/lines/): a Shiny web app that illustrates linear models. Especially helpful to understand interactions.
- [One Thousand and One names](https://stefanocoretta.github.io/post/2022-07-22-one-thousand-and-one-names/): table with naming conventions for different types of linear models.
- [Linear Models: A cheat-sheet](https://stefanocoretta.github.io/post/2021-08-21-regression-models-a-cheat-sheet/): use this to find out which building blocks you need for your linear model.
:::


### Week 11: Obtaining *p*-values (Optional)

::: {.callout-tip collapse="false"}
#### Materials

-   [Lecture slides](slides/w11/).
-   [Workshop tutorial](tutorials/tutorial-w11.qmd).
:::

::: {.callout-tip collapse="false"}
#### Suggested readings

- [Motulsky 2014](https://doi.org/10.1007/s00210-014-1037-6), *Common misconceptions about data analysis and statistics*.
- [Tressoldi et al 2015](https://doi.org/10.2139/ssrn.2579268), *The pervasive avoidance of prospective statistical power: Major consequences and practical solutions*.
- [Cassidy et al 2019](https://doi.org/10.1177/2515245919858072), *Failing grade: 89 per-cent of introduction to psychology textbooks that define/explain statistical significance do so incorrectly*.
- [Gigerenzer 2004](https://doi.org/10.1016/j.socec.2004.09.033), *Mindless statistics*.
- [Wagenmakers 2007](https://doi.org/10.3758/BF03194105). *A practical solution to the pervasive problems of p-values*.
- [Interpreting (frequentist) Confidence Intervals](https://rpsychologist.com/d3/ci/).
:::

### Week 12

::: {.callout-warning}
#### Summative 2: Week 12 (Thu 7 December at noon)

**Due on Thursday 7 December at noon**

In the second summative assessment, you will:

-   Select a dataset from a list and its associated research questions.
-   Analyse the data using one linear model.
-   Write a report about the data, the model, and your findings.

You can find the instructions and data for the first summative here: <https://github.com/uoelel/qml-s2/>.

:::
