---
title: "Research Methods in Developmental Linguistics"
---

This site contains materials of the course *Research Methods in Developmental Linguistics* (Semester 2).

::: {.callout-tip}
## Ask for help

If at any point during the course you don't feel comfortable with any aspect of the course, you are unsure about anything that has been covered in class or in your own time, you are struggling to keep up with the course workload, you are experiencing mental of physical distress due to a pre-existing or new illness, medical condition or disability, or you find yourself unable to access basic needs like food or housing, **please do get in touch with me and/or the PPLS support** (*go to the PPLS UG or MSc Hub on SharePoint \> Support for students \> Health & Wellbeing*).

We are humans first and the rapidly-changing new world we are living in now can put us under pressure. What is most important to me is that you are first and foremost healthy and able to participate to the course, and that you succeed and get the most out of the course.

**It is OK not to be OK, and remember that you are not alone.** Other people, teachers and students, might be struggling right now or have struggled before and might have gone through what you are going through now. Remember that support exists for you, so please do reach out. If you see somebody close to you struggling, please let them know about the available support network and encourage them to reach out.
:::

::: {.callout-warning}
## Contacts

You can reach Stefano at [s.coretta\@ed.ac.uk](mailto:s.coretta@ed.ac.uk){.email} or on Teams.

If you want to book **office hours** with Stefano, you can do so here: <https://bit.ly/33BH84L>.
:::
