---
title: "Research Methods in Developmental Linguistics"
subtitle: "Week 5"
author: "Dr Stefano Coretta"
institute: "University of Edinburgh"
date: "2024/02/12"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css:
      - ../xaringan-themer.css
      - ../custom.css
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      beforeInit: "../macros.js"
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width=7, fig.height=5, fig.retina=3,
  out.width = "60%", fig.align = "center",
  cache = FALSE,
  echo = TRUE,
  message = FALSE, 
  warning = FALSE,
  hiline = TRUE
)
knitr::opts_knit$set(root.dir = here::here())

library(tidyverse)
theme_set(theme_light())

library(brms)
library(tidybayes)

library(xaringanExtra)
use_xaringan_extra(c("panelset", "tachyons", "freezeframe"))

options(ggplot2.discrete.fill = RColorBrewer::brewer.pal(8, "Dark2"))
options(ggplot2.discrete.colour = RColorBrewer::brewer.pal(8, "Dark2"))
options(show.signif.stars = FALSE)

my_seed <- 8878
set.seed(my_seed)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_light(outfile = "slides/xaringan-themer.css", link_color = "#7E3817")
```

layout: true

## Ota 2009

---

[STUDY DESCRIPTION]

---

```{r ota2009}
ota2009 <- read_csv("data/ota2009.csv") %>%
  filter(
    Procedure == "TrialProc", Contrast != "F"
  ) %>%
  mutate(
    Subject = as.factor(Subject), RT_log = log(Words.RT)
  )
ota2009
```

---

```{r fig-contr-cond, echo=FALSE}
ota2009 %>%
  ggplot(aes(Contrast, RT_log)) +
  geom_violin(aes(fill = Condition), alpha = 0.2) +
  geom_jitter(
    aes(colour = Condition), alpha = 0.4,
    position = position_jitterdodge(jitter.width = 0.1, dodge.width = 0.9)
  ) +
  stat_summary(
    aes(group = Condition),
    position = position_dodge(width = 0.9),
    fun = "median", geom = "point", size = 3
  )
```

---

```{r fig-subj-int, echo=FALSE, fig.asp=0.5}

ota2009 %>%
  filter(Contrast == "LR") %>%
  ggplot(aes("a", RT_log)) +
  geom_violin() +
  geom_jitter(
    aes(colour = Subject), alpha = 0.4,
    width = 0.1
  ) +
  stat_summary(
    position = position_dodge(width = 0.9),
    fun = "median", geom = "point"
  ) +
  facet_wrap(~ Subject, nrow = 2) +
  labs(x = element_blank()) +
  theme(
    axis.text.x = element_blank(),
    legend.position = "none"
  )
```

---

```{r fig-subj-slo, echo=FALSE, fig.asp=0.5}

ota2009 %>%
  filter(Contrast == "LR") %>%
  ggplot(aes(Condition, RT_log)) +
  geom_violin(aes(fill = Condition), alpha = 0.5) +
  # geom_jitter(
  #   aes(colour = Condition), alpha = 0.4,
  #   position = position_jitterdodge(jitter.width = 0.1, dodge.width = 0.9)
  # ) +
  stat_summary(
    aes(group = Condition),
    position = position_dodge(width = 0.9),
    fun = "median", geom = "point"
  ) +
  facet_wrap(~ Subject, nrow = 2) +
  theme(axis.text.x = element_blank(), legend.position = "bottom")
```

---

```{r ota-bm-1}
ota_bm_1 <- brm(
  RT_log ~ Condition * Contrast,
  family = gaussian,
  data = ota2009,
  backend = "cmdstanr",
  seed = my_seed,
  file = "data/cache/ota_bm_1"
)
```

---

```{r ota-bm-1-sum}
summary(ota_bm_1, prob = 0.9)
```

---

```{r ota-bm-1-gdraws}
ota_bm_1_gdraws <- ota_bm_1 %>%
  gather_draws(`b_.*`, regex = TRUE)
```

---

```{r }
ota_bm_1_gdraws %>%
  filter(.variable != "b_Intercept") %>%
  ggplot(aes(.value, .variable, fill = .variable)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  stat_halfeye(slab_alpha = 0.5) +
  theme(legend.position = "none")
```

---

```{r}
ota_bm_1_sdraws <- ota_bm_1 %>%
  spread_draws(`b_.*`, regex = TRUE) %>%
  mutate(
    LR_cond_dif = b_ConditionUnrelated + `b_ConditionUnrelated:ContrastLR`
  )
ota_bm_1_sdraws
```

---

```{r}
ota_bm_1_sdraws %>%
  ggplot(aes(LR_cond_dif)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  stat_halfeye(slab_alpha = 0.5)
```

---

```{r ota-bm-2}
ota_bm_2 <- brm(
  RT_log ~
    Condition * Contrast +
    (1 | Subject),
  family = gaussian,
  data = ota2009,
  backend = "cmdstanr",
  seed = my_seed,
  file = "data/cache/ota_bm_2"
)
```

---

```{r}
summary(ota_bm_2, prob = 0.9)
```

---

```{r}
ota_bm_2_sdraws <- ota_bm_2 %>%
  spread_draws(`b_.*`, regex = TRUE) %>%
  mutate(
    LR_cond_dif = b_ConditionUnrelated + `b_ConditionUnrelated:ContrastLR`
  )
ota_bm_2_sdraws
```

---

```{r}
ota_bm_2_sdraws %>%
  ggplot(aes(LR_cond_dif)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  stat_halfeye(slab_alpha = 0.5)
```

---

```{r}
ota_bm_2_int <- ota_bm_2 %>%
  gather_draws(r_Subject[Subject,term])
ota_bm_2_int
```

---

```{r}
ota_bm_2_int %>%
  ggplot(aes(.value, reorder(as.factor(Subject), .value))) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  stat_halfeye()
```

